const rides = [
    {
      name: "Hero Destiny 110",
      id: 1,
      url: require("../../assets/bikesimage/scooty1.png"),
      availability: 2,
      price: 450,
      fuel: "Petrol",
      brand: "Hero",
      segment: "Urban",
    },
    {
      name: "Vespa",
      id: 2,
      url: require("../../assets/bikesimage/scooty2.png"),
      availability: 1,
      price: 400,
      fuel: "Petrol",
      brand: "Vespa",
      segment: "Luxury",
    },
    {
      name: "Yamaha Ray Z",
      id: 3,
      url: require("../../assets/bikesimage/scooty3.png"),
      availability: 3,
      price: 500,
      fuel: "Petrol",
      brand: "Yamaha",
      segment: "Street",
    },
    {
      name: "Ray ZR Street",
      id: 4,
      url: require("../../assets/bikesimage/scooty4.png"),
      availability: 2,
      price: 400,
      fuel: "Electric",
      brand: "Ray",
      segment: "Urban",
    },
    {
      name: "Vespa 2",
      id: 5,
      url: require("../../assets/bikesimage/scooty5.png"),
      availability: 4,
      price: 350,
      fuel: "Electric",
      brand: "Vespa",
      segment: "Street",
    },
  ];